### ISSUE TITLE
Shared memory pre-allocation

### ISSUE THREAD

**Issue by Narasimha1997** [NVIDIA/tensorrt-inference-server#1119]
I am having a doubt regarding CUDA shared memory. Is it possible to allocate memory for max batch size and run inference for batches lesser than max-batch-size?

For example : If I have a model with max-batch-size of 32, but during the inference time, I have only 10 inputs, but the shared memory is already allocated for 32 batch size. Is it possible to run inference only for 10 inputs? or do I need to re-allocate memory for 10 batch size? 

Any help is appreciated.

**Comment by CoderHam** [comment]
Yes you can create a CUDA shared memory region of size equal to that for the max batch size and run inference with a size smaller than that size. You are essentially creating a CUDA shared memory and using a subset of that memory for a specific inference. We have tests that do the same. Our python client API is limited in it's support but if you are using the C++ client API you should be golden.

Look [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c++/examples/simple_cuda_shm_client.cc#L243) at our simple cuda shared memory client example.

**Comment by Narasimha1997** [comment]
But this is what the comment in test-case shows : 
`def test_too_big_shm(self):
        # Shared memory input region larger than needed - Throws error
        error_msg = []
        shm_handles = self._configure_sever()
        shm_ip2_handle = cshm.create_shared_memory_region("input2_data", 128, 0)
        shared_memory_ctx = SharedMemoryControlContext(_url,  _protocol, verbose=True)
        shared_memory_ctx.cuda_register(shm_ip2_handle)
        self._basic_inference(shm_handles[0], shm_handles[1], shm_handles[2], shm_handles[3], error_msg)
        if len(error_msg) > 0:
            self.assertTrue(error_msg[-1] == "The input 'INPUT1' has shared memory of size 128 bytes"\
                                    " while the expected size is 1 * 64 = 64 bytes")
        shm_handles.append(shm_ip2_handle)
        self._cleanup_server(shm_handles)`


"Shared memory input region larger than needed - Throws error"

**Comment by CoderHam** [comment]
This is because we build a custom wrapper around cuda shared memory.  Since there does not exist a python library for the same. If you wish to have the same feature you can build or extend your own wrapper. 

https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/api_v1/library/cuda_shared_memory/cuda_shared_memory.cc

I would however advise to use the C++ library to get the complete benefit of cuda shared memory (especially if performance is your concern).

**Comment by Narasimha1997** [comment]
Okay, thanks, will work on using C++. Can you let me know where you are checking that size constraint?

**Comment by CoderHam** [comment]
It was a decision to simplify the python wrapper for cuda and system shared memory. 

Like in [shared_memory.cc](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/api_v1/library/shared_memory/shared_memory.cc#L72)

You can see that the function creates, mmaps the shared memory region of the exact size as requested. This means that the entire shared memory region is used for the request. Each region represents the payload for that Input/Output for that request. 
If you wish to you may break this function up into individual functions for creating, mmaping, assigning to a specific shared memory handle. 

Since that would considerably complicate the client we chose to avoid this approach. You should read up about the rules/limitations imposed by mmap before you do this to see if the overhead and rules will be a hurdle for you.
