### ISSUE TITLE
Safeguard one model from failures in others

### ISSUE THREAD

**Issue by emirkin** [NVIDIA/tensorrt-inference-server#1140]
#1102 begs for another question -- why should a failure in one model (memory leak or otherwise), bring down other models served by the same TRTIS process? Can you add a mechanism to protect models from one another or, at the very least, restart failed models?

**Comment by deadeyegoodwin** [comment]
The models share the common GPU memory. If one model uses all the GPU memory and the other model needs to allocate some to perform an inference then that inference will fail. There isn't really anything TRTIS can do about not having enough GPU memory. We have thought about using UVM so that GPU memory could be oversubscribed or automatically managing models and/or failed inference requests... but such solutions are complex and potentially ineffective.

Retries could be handled at a higher-level. Model orchestration (the term we use for managing which models go on which servers/GPUs to avoid OOM and meet SLA/SLO requirements) could benefit from some additional tools that we do have on our longer-term roadmap. These tools would help you characterize and manage you model repositories so you could avoid OOM situations.
