### ISSUE TITLE
Error "NotImplementedError: memoryview: unsupported format <b"

### ISSUE THREAD

**Issue by banhbaomocmeo** [NVIDIA/tensorrt-inference-server#1171]
**Description**
I run client code and get this error
`  File "/home/nano1/Desktop/client/model_parser.py", line 38, in parse_model
    server_status = ctx.get_server_status()
  File "/home/nano1/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 632, in get_server_status
    status.ParseFromString(status_buf)
  File "/home/nano1/.local/lib/python3.6/site-packages/google/protobuf/message.py", line 187, in ParseFromString
    return self.MergeFromString(serialized)
  File "/home/nano1/.local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1127, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/nano1/.local/lib/python3.6/site-packages/google/protobuf/internal/python_message.py", line 1163, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "/home/nano1/.local/lib/python3.6/site-packages/google/protobuf/internal/decoder.py", line 192, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
NotImplementedError: memoryview: unsupported format <b
`

inference server run ok, 
it ran ok when i tested server with client which run in docker (ubuntu 18.04, tensorrtserver: 1.12.0dev0) and i run both on PC.
i got this error when server (run on PC) and client (run on jetnano, tensorrtserver: 1.11.0)

**TRTIS Information**
server side: using docker
 - device: PC (core i9, ubuntu 18.04)
 - image: nvcr.io/nvidia/tensorrtserver:20.01-py3

client side: build it myself
 - device: jetson nano (jetpack 4.2.1)
 - tensorrtserver: 1.11.0 (r20.02)

Thank you for notice

**Comment by CoderHam** [comment]
This was fixed in the 20.03 release. You can apply the patch from [here](https://github.com/NVIDIA/tensorrt-inference-server/commit/8c55ddd13f5178f7057c89560d59789c85c75b11#diff-763212ba4e9385495d77b6bcfac87129L631) in the [__init__.py](https://github.com/NVIDIA/tensorrt-inference-server/commit/8c55ddd13f5178f7057c89560d59789c85c75b11#diff-763212ba4e9385495d77b6bcfac87129) and [crequest.cc](https://github.com/NVIDIA/tensorrt-inference-server/commit/8c55ddd13f5178f7057c89560d59789c85c75b11#diff-6263c1eefc85691d6ba6e49e853122d3)

The issue is caused by improper serialization of the protobuf buffer to string in the `SerializeToString`. function on Jetson. The fix simply uses the short debug string format instead and parse using the `text_format.Parse` function.

**Comment by banhbaomocmeo** [comment]
I've switched to branch r20.03 then rebuilt client and it works well. Thank for supporting

**Comment by rounakskm** [comment]
@banhbaomocmeo How did you build the wheel I am getting Could not find VERSION
