### ISSUE TITLE
image_client demos don't support dynamic input/output shapes

### ISSUE THREAD

**Issue by erickim555** [NVIDIA/tensorrt-inference-server#162]
I am on commit [0ae29b89066b7ee1a565985b753673bc1e179a31](https://github.com/NVIDIA/tensorrt-inference-server/commit/0ae29b89066b7ee1a565985b753673bc1e179a31), and the image_client demos (both C++ and Python) do not support variable-sized input/output tensors, specifically for the Caffe2 backend (and possibly for the tensorflow/tensorrt backends as well, I haven't checked). 

For instance, running the python image_client with the model.pbtxt input dims being `dims: [ 3, -1, -1 ]` gets this error message when running the Python image_client:

```
Exception: variable-size dimension in model input not supported
```

**Comment by deadeyegoodwin** [comment]
That looks like a commit on master... working on master is always subject to intermittent weirdness since we are actively developing there. If you want a stable version I suggest 19.02 as it was recently released and has pre-build clients bits included in the release assets.

That said, the problem you are hitting is not in the inference server, It is that the image_client needs to know the exact size of the input so that it can pre-process the input image to that size. If the input can take on any size then it doesn't know what to do. You can fix by changing your model config to have an exact input size (this is ok to do even if the underlying model supports any size). Or you could add arguments to image_client that let to explicitly specify the input dimensions for cases where the model itself accepts variable-size. That would be a nice contribution.

**Comment by deadeyegoodwin** [comment]
Closing, reopen if you still have an issue.
