### ISSUE TITLE
Feature Request: Add Go Client

### ISSUE THREAD

**Issue by gaocegege** [NVIDIA/tensorrt-inference-server#175]
TensorRT Inference Server is an awesome tool to serve DL models in the cloud. While I think we could implement an official Go client for Go users, which is a popular language in Kubernetes and cloud community.

**Comment by deadeyegoodwin** [comment]
We would be happy to consider a contribution of a go client that implements the existing client API. But note that because TRTIS supports a GRPC API you can generate a Go client using protoc. It is likely you can just add --go_out flag to protoc invocation in Makefile.client (as described here: https://grpc.io/docs/tutorials/basic/go.html). Note that https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/grpc_image_client.py shows an example using the protoc-generated API for Python.

**Comment by gaocegege** [comment]
Thanks for your comment!

Thanks for the information, I used the pb interface generated by protoc and it worked. I think it will be more convenient if we have a go client.

**Comment by akurniawan** [comment]
hi @GuanLuo , do you mind to share your go client code? I think that would be useful for other people that want to create go client for their app as well

**Comment by gaocegege** [comment]
https://github.com/gaocegege/tensorrt-inference-server/tree/master/src/clients/golang/nvidia_inferenceserver

@akurniawan I only tested status API.

```go
                conn, err := grpc.Dial(endpoint, grpc.WithInsecure())
		if err != nil {
			return err
		}
		defer conn.Close()
		client := nvidia_inferenceserver.NewGRPCServiceClient(conn)
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		response, err := client.Status(ctx, &trtis.StatusRequest{})
		if err != nil {
			return err
		}
```

**Comment by akurniawan** [comment]
cool, thanks!

Ah yes, I think I chose the wrong autocomplete option. Thanks for that

**Comment by deadeyegoodwin** [comment]
@rmccorm4 contributed a Go client example with #639

**Comment by rmccorm4** [comment]
@gaocegege @akurniawan hope this helps 🙂
