### ISSUE TITLE
TYPE_STRING: failed to set result for entire batch

### ISSUE THREAD

**Issue by bezero** [NVIDIA/tensorrt-inference-server#192]
I have created a simple model that receives an array, calculates mean and returns the result as a string output. Code that produces and creates the frozen model is:
```py
import tensorflow as tf
input_data = tf.placeholder(tf.int32, shape=(None, 1, 3), name='input')
reduce_mean = tf.reduce_mean(input_data)
output = tf.dtypes.as_string(reduce_mean, name='output')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    input_graph_def = sess.graph.as_graph_def()
    output_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,  # The session is used to retrieve the weights
        input_graph_def,  # The graph_def is used to retrieve the nodes
        ['output']  # The output node names are used to select the usefull nodes
    )
    with tf.gfile.GFile('model.graphdef', "wb") as f:
        f.write(output_graph_def.SerializeToString())
```

For serving I used ```tensorrtserver:19.03-py3```. ```config.pbtxt``` file is as follows:
```
name: "mean"
platform: "tensorflow_graphdef"
max_batch_size: 5
input [
    {
        name: "input"
        data_type: TYPE_INT32
        dims: [1, 3]
    }
]
output [
    {
        name: "output"
        data_type: TYPE_STRING
        dims: [1]
    }
]
```

When I send a simple request with a dummy data I receive ```NV-Status: code: SUCCESS```  and
```
HTTP/1.1 200 OK
NV-InferResponse: model_name: "mean" model_version: 1 batch_size: 2 output { name: "output" raw { batch_byte_size: 79 } }
NV-Status: code: SUCCESS server_id: "inference:0" request_id: 2
Content-Type: application/octet-stream
Content-Length: 103

ResponseHandler: [ 0] INTERNAL - output 'output' failed to set result for entire batch
* Failed writing body (0 != 103)
* Closing connection 0
```

I think this is because of the network output. It is a binary string as far as I know; however, TRTIS is not able to convert it to a regular string value for the client. Is it because of the server or client? How can I solve this issue?

**Comment by deadeyegoodwin** [comment]
I think the network you are generating is not what you expect, though I am not sure why as I'm not a TF export. Using graphdef makes it hard to see what is going on (graphdef is painfully lacking on information about inputs and outputs). So I modified your script to save the model using savedmodel format.

```
import tensorflow as tf
input_data = tf.placeholder(tf.int32, shape=(None, 1, 3), name='input')
reduce_mean = tf.reduce_mean(input_data)
output = tf.dtypes.as_string(reduce_mean, name='output')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    tf.saved_model.simple_save(sess, "/tmp/model.savedmodel",
                               inputs={"input": input_data},
                               outputs={"output": output})
```

Using saved-model will enable TRTIS to give better error messages and also allow it to generate the config.pbtxt for you. Create a model-store like this:
```
/tmp/models/
  mean/
    1/
      model.savedmodel/
        <contents>
```

Then,
$ trtserver --model-store=/tmp/models --strict-model-config=false

The --strict-model-config flag tells TRTIS that it is free to try to generate missing parts of the config.pbtxt. Since you don't have any config.pbtxt it will try to generate the whole thing. It will fail for your case but you can still see what it tried to do by using --log-verbose=1.

When I do that I see the following. signature_def is from the savedmodel meta-data and tells us about the model inputs and outputs.

```
signature_def {
  key: "serving_default"
  value {
    inputs {
      key: "input"
      value {
        name: "input:0"
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: -1
          }
          dim {
            size: 1
          }
          dim {
            size: 3
          }
        }
      }
    }
    outputs {
      key: "output"
      value {
        name: "output:0"
        dtype: DT_STRING
        tensor_shape {
        }
      }
    }
    method_name: "tensorflow/serving/predict"
  }
}
```
This says that the output has shape [ ], meaning it is empty/nothing. TRTIS doesn't know what to do with a model that produces nothing. Because the graphdef doesn't have this kind of information you were able to define a invalid config.pbtxt and it couldn't detect that until inference time.

Can you try modifying your model to see if you can get it to produce a non-zero-sized output.

**Comment by deadeyegoodwin** [comment]
Two things. 
First, since the model doesn't support batching in the way that TRTIS can understand, be sure to set max_batch_size = 0 in the model config.
Second, "dims" cannot have 0 dimensions and cannot be zero sized. The "dims" represent the shape of the input and output tensors as expected/reported by the TRTIS API. It doesn't make sense to have an input or output that is always zero size. 

There is a related feature on the master branch (will be in 19.04 release) called "reshape" that allows you to reshape the "dims" shape into something expected by the model, but that doesn't allow you to have an empty/zero "dims".

**Comment by deadeyegoodwin** [comment]
@bezero I should have also mentioned another option. If you set dims [ -1 ] in your model configuration, then you can have an input/output with zero size because a request can use a tensor with shape [ 0 ] (the -s can take on any value >= 0).
