### ISSUE TITLE
trtis uses too much ram

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA/tensorrt-inference-server#207]
hello every one.
when i deploy my models (3 model - total: 250M), my computer use 9.6GB ram. 
i don't know why.
please help me to fix this problem.
![Screenshot from 2019-04-05 15-57-11](https://user-images.githubusercontent.com/48821989/55616216-8433d100-57bb-11e9-96d4-f3dd3a21f439.png)

**Comment by bezero** [comment]
I think you are deploying TF models. TRTIS loads model to the GPU which is initially small. When you send a batch request to one of your models, memory footprint increases. Next time, when you send request for the next model, TRTIS offloads that increased GPU model to your CPU RAM and uploads requested model to GPU. This way you CPU RAM keeps increasing.

You can control these increases by setting smaller `max_batch_size`. You also can convert your models to TRT plan, which will have fixed size footprint on your GPU, which will decrease you CPU RAM load.
You can find more detailed explanation by @deadeyegoodwin in #145

**Comment by royinx** [comment]
I am trying to run the trtis on local pc 2070, with 2 tensorRT plan (yolo) 
while testing the throughput of trtis, the memory raise rapidly. 

Even i shut down the client container, the DRAM stuck in 10GB out of 16GB 
- trtis off: 3.6GB
- trtis on: 6.8 GB
- after the 10requests: 16GB+2GB swap

if i keep sending the request and receive the result, the server DRAM still goes up and eat up all the swap. 

but VRAM keep the same with 6GB out of 8GB.

1). Is there any configuration i have to set inside config.pbtxt that release memory/cache?

2).another question, how can i know the trtis cpu usage and throughput of each model (since there are network latency on sending data)?



```
name: "yolov3_608_trt"
platform: "tensorrt_plan"
max_batch_size: 32
dynamic_batching {
  preferred_batch_size: [ 4, 8 ,16, 24, 32]
  max_queue_delay_microseconds: 100
}
input [
  {
    name: "000_net"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 608, 608 ]
  }
]
output [
  {
    name: "082_convolutional"
    data_type: TYPE_FP32
    dims: [ 255, 19, 19 ]
  },
  {
    name: "094_convolutional"
    data_type: TYPE_FP32
    dims: [ 255, 38, 38 ]
  },
  {
    name: "106_convolutional"
    data_type: TYPE_FP32
    dims: [ 255, 76, 76 ]
  }
]


instance_group [
  {
    count:2
    kind: KIND_GPU
  }
]
```
