### ISSUE TITLE
Implement Pre-process "add-on" to reduce TRTIS communication bottleneck

### ISSUE THREAD

**Issue by pmcgraw-lucidyne** [NVIDIA/tensorrt-inference-server#25]
Hello I am looking improve the performance of my client application which runs nets on TRTIS that take large inputs (think batches of 10 tensors of size (2048, 512, 8)) and outputs tensors (2048, 512, 9) by implementing a custom pre-process step. deadeyegoodwin mentioned in a reply to a user's question about submitting raw data via IPC that it is possible to implement a pre-process add-on to be built into TRTIS. Could anyone point me towards some resources so I can more quickly implement a first past at this feature? 

Bellow is the comment from deadeyegoodwin that I refer to above. I am interested in item two because it seems to be the performance solution I can use:

In general I think your assessment is correct: I/O can be a performance limiter for some models and a primary way to fix this in many cases is to make the pre-processing local with the inference. Here are some variations we think about and where we stand as far as current support:

1. Pre-processing "service" running on same node as TensorRT Inference Server (TRTIS).
    a. Use GRPC (or HTTP) to communicate from pre-processor -> TRTIS. Since communication is now local it may no longer be a bottleneck...
    b. For even higher BW between pre-processor -> TRTIS, remove the GRPC/HTTP protocol overhead by implementing a custom/raw socket API. The internal APIs to allow this are already available within TRTIS and we plan to formalize and document them better in the future. Another option here is a flatbuffer interface which we have also thought about but not done anything with as yet.
    c. Use shared-memory as you suggest... this would likely require a custom TRTIS API to communicate the shared-memory reference so is similar to (b).
    d. For maximum bandwidth you could share GPU memory between pre-processor and TRTIS and use that for communication. The pre-processor would leave the input tensors in GPU memory and just share the location (via CUDA IPC) with TRTIS. We want to add some functionality to TRTIS to support this but currently we have not.
2. Avoid communication completely by implementing the pre-processor within TRTIS. Again, the  
internal APIs to allow this are already available within TRTIS and we plan to formalize and document them better in the future. In general we are interested in generic pre-processor "add-ons" of this kind that we can incorporate into TRTIS as build-time options.

I would suggest that you start with (1a) and see how much benefit that gets you. We are generally interested in improving TRTIS in this area and so would welcome your experience and feedback as you experiment. If you think you could contribute something generally useful we would be very open to working with you on it, just be sure to include us in your plans early on so we can make sure we are all on the same page.

As for your question #3. Yes, for experimenting it is probably fastest to hack up the gRPC service to instead pass the reference instead of the actual data (but keep the rest of the request/response message the same). infer.cc is where the data (raw_input) is read out of the request message so you would need to change that to instead read from shared memory.

_Originally posted by @deadeyegoodwin in https://github.com/NVIDIA/tensorrt-inference-server/issues/1#issuecomment-441766955_

**Comment by deadeyegoodwin** [comment]
You mention both IPC and pre-process add on. These are two alternatives to solve your problem.

By using IPC to communicate the tensors you avoid any communication overhead between your process performing custom pre-processing and TRTIS, since they communicate through shared-memory. In https://github.com/NVIDIA/tensorrt-inference-server/issues/1#issuecomment-444307466 there is a patch to do some form of IPC. We haven't looked at it in detail so not sure how applicable it is for you. On our roadmap we have plans for official IPC support but no release date yet.

But I think you are more interested in building a pre-processor into TRTIS. That is also on our roapmap but is a significant effort. Our thinking right now is that we'd like to allow pre-processor extensibility of the kind you mention by allowing custom pre-processor passes to be packaged as shared libraries that can be associated with a model. The shared library would implement an API defined by TRTIS that would accept a "binary blob" and produce the input tensors expected by the model.

As a conceptual example see the custom backend interface in src/servables/custom/custom.h. An example shared library that implements that interface is in src/custom/addsub. You can also read some about this custom backend support in the docs. (This is all on the master branch right now and will be released in 19.01).

To do something similar for pre-processing we likely need a couple of things:
* A new HTTP/GRPC API to send data to the model with one of these custom pre-processors. Ideally it would just be a new option on the existing infer API in api.proto and grpc_service.proto. Perhaps just reuse the input tensor as a way to pass "binary blob(s)" to the pre-processor logic.
* Enhancement to the model configuration (model_config.proto) to allow specification of the pre-processing shared library (perhaps just a path to the shared library).
* The pre-processing interface (similar to what custom.h does for the custom backend) that describes and interface that takes the input "binary blob" and produces the input tensors required by the model.
* The manager / handler logic in TRTIS that loads these shared libraries and then invokes them appropriately to get the input tensors before executing the ML model. Invoking the pre-processor would likely happen in server.cc: HandleInfer.

**Comment by pmcgraw-lucidyne** [comment]
I will look into IPC first and work my way towards preprocessing. I'll
comment on the issue with any progress towards TRTIS specific stuff.

**Comment by deadeyegoodwin** [comment]
Note that we now have ensembling on the master branch as well as an example that uses a custom backend to perform the actual image pre-processing and then feeds the result into a resnet50 model.

See:
https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/models_and_schedulers.html#ensemble-models
https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/client.html#ensemble-image-classification-example-application

IPC is still on our roadmap and we are tracking that separately so I'm going to close this issue.

**Comment by mrjackbo** [comment]
Will the current ensembling features be in the 19.05 release?

**Comment by deadeyegoodwin** [comment]
Yes
