### ISSUE TITLE
Jmeter failed to get response from trtis

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/tensorrt-inference-server#258]
Hello:
     I want to use Jemter to make a test for trtis server, the model I used is the simple model from model_respository, but I can not get the response from the server. the error is :
Response code: Non HTTP response code: org.apache.http.NoHttpResponseException
Response message: Non HTTP response message: localhost:8000 failed to respond

HTTPSampleResult fields:
ContentType: 
DataEncoding: null

and my request headers is like:
Connection: close
: 
Content-Type: application/octet-stream
NV-InferRequest: batch_size: 1 input { name: 'INPUT0'} input { name: 'INPUT1'} output { name: 'OUTPUT0'} output {name: 'OUTPUT1'}
Content-Length: 128
Host: localhost:8000
User-Agent: Apache-HttpClient/4.5.7 (Java/11.0.2)

I had use python client and curl to access this server successfully,  is there anyone help me to give me some suggestion ?
Thank you in advance !

**Comment by deadeyegoodwin** [comment]
[jmeter.zip](https://github.com/NVIDIA/tensorrt-inference-server/files/3133059/jmeter.zip)

We just jmeter for one of our CI tests. We don't include this CI test in the open-source repo because it depends on models which we can't distribute. But I've attached the jmeter config file and the test.sh script for it that you should be able to read and modify to use models that you have available.
