### ISSUE TITLE
Dynamic batch size for input with shape -1

### ISSUE THREAD

**Issue by akurniawan** [NVIDIA/tensorrt-inference-server#270]
According to this https://github.com/NVIDIA/tensorrt-inference-server/blob/115752fc53602804f0ca331872efe74e75c571ff/src/core/dynamic_batch_scheduler.cc#L52

It seems right now TRIST does not support dynamic batching for models like RNN where one of the input shapes could be dynamic. Is my understanding correct? If it's yes then is there any plan or workaround to enable this?

**Comment by deadeyegoodwin** [comment]
You are correct that this is a limitation... and it arises because TRTIS would need some additional information to be able to handle the case correctly. Consider you have a model that takes a variable-sized input:

max_batch_size: 4
input {
  name: "INPUT"
  dims: [ -1 ]
}
...

So TRTIS (and the underlying model) are expecting input to have shape [ -1, -1 ]. The first dimension is the batch dimension and is what TRTIS will use to form dynamic batches and pass them to the model. Even though the model can accept any size matrix (2d tensor), it does have to be a complete matrix. 

For example, assume two batch-size 1 requests are made, each with shape [ 1, 16 ]. TRTIS can dynamically batch them into a single execution of the model using an input tensor with shape [ 2, 16 ]. 

Now consider that the two batch-size 1 requests have different shapes, [ 1, 16 ] and [ 1, 20 ]. How can TRTIS batch thes into a single matrix? Perhaps it could use [ 2, 20 ] and pad the first request... but how would it pad? With zeros or some other value? Should it pad at the start or end? In general TRTIS can't handle this case. Perhaps we could add additional model configuration that would allow the model to describe how to handle these situations but currently we don't.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you have further questions

**Comment by axmadjon** [comment]
@akurniawan 
look [this doc](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/protobuf_api/api.proto.html#_CPPv4N6nvidia15inferenceserver18InferRequestHeader5Input4dimsE)

i solved 
request.meta_data.input.add(name=input_name, dims=[height, width, color])

**Comment by mcf330** [comment]
Save issue for me, anyone can provide a workaround?  Thanks.

**Comment by mcf330** [comment]
@axmadjon 
Can you show more implementation details. Thanks

**Comment by akshayrana30** [comment]
> Perhaps we could add additional model configuration that would allow the model to describe how to handle these situations but currently we don't.
@deadeyegoodwin Any plans to handle dynamic batching for requests with variable sequence length?

**Comment by deadeyegoodwin** [comment]
There is some support for ragged batching but it is not yet documented. See  qa/L0_trt_batch_input and https://github.com/triton-inference-server/server/blob/master/src/core/model_config.proto#L403

**Comment by chunyulin** [comment]
Hi @deadeyegoodwin, I tried to modify [our original model config](https://github.com/fastmachinelearning/sonic-models/blob/master/models/particlenet_AK4/config.pbtxt) to support ragged batch as in the code you mentioned. But the Triton server cannot start due to 
```
I1103 08:54:56.069533 5266 server.cc:220] Waiting for in-flight requests to complete.
I1103 08:54:56.069542 5266 server.cc:235] Timeout 30: Found 0 live models and 0 in-flight non-inference requests
error: creating server: Internal - failed to load all models
```
My original model input looks like this:
```
input [
  {
    name: "input0"
    data_type: TYPE_FP32
    dims: [ 2, -1 ]
  }
]
```
And I changed it to 
```
input [
  {
    name: "input0_RAGGED"
    data_type: TYPE_FP32
    dims: [ 2, -1 ]
    allow_ragged_batch: true
  }
]
batch_input [
  {
      kind: BATCH_MAX_ELEMENT_COUNT_AS_SHAPE
      target_name: "input0"
      data_type: TYPE_FP32
      source_input: "input0_RAGGED"
  }
]
```
Could you help to check my modification?

**Comment by deadeyegoodwin** [comment]
Look in the console log for lines starting with E1103 to see why your model failed to load.

**Comment by chunyulin** [comment]
Oops, I didn't notice the error line. It's a version issue. Thanks. 
```
E1103 22:04:06.883611 5305 model_repository_manager.cc:1682] ragged-batch input tensors are only supported for custom platform and TensorRT platform for particlenet_AK4
```

**Comment by deadeyegoodwin** [comment]
You are using an older Triton that did not support ragged batching for onnxruntime backend. You need to update to a recent Triton where it is supported.
