### ISSUE TITLE
Execution of models in ensemble does not depend on requested outputs

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#289]
On the current master branch, I have a model MainEnsemble with input INPUT and outputs OUTPUT_A, OUTPUT_B. The ensemble is made of three "models":

step 1: Preprocess. Input: INPUT, Output: Preprocessed_A, Preprocessed_B
step 2: Model_A. Input Preprocessed_A, output OUTPUT_A
step 3: Model_B, Input Preprocessed_B, output OUTPUT_B

When I use the python client library to request OUTPUT_A, I get OUTPUT_A, but Model_B is still evaluated, even though its output is not used. The same happens if I request OUTPUT_B.
 Is this expected behavior?

(My actual setup is more complicated. Model_A and Model_B are ensembles themselves, if that's relevant, and edges between Preprocess and Model_A/B are actually two tensors)

**Comment by GuanLuo** [comment]
Yes in respect to current implementation. In the current implementation, a model will be evaluated as long as the inputs it requires is set.

But the scenario you mentioned shows a possible enhancement, as we can refine the data flow based on the requested outputs so that less models are run for the request.

**Comment by deadeyegoodwin** [comment]
Marked as enhancement. We should prune the ensemble based on requested outputs.

**Comment by GuanLuo** [comment]
#638 Improved ensemble to be aware of requested outputs.
