### ISSUE TITLE
nv_inference_load_ratio_bucket

### ISSUE THREAD

**Issue by allenc97** [NVIDIA/tensorrt-inference-server#295]
Quick question regarding the prometheus metric load ratio. What is load ratio percentage referring to here?

**Comment by deadeyegoodwin** [comment]
Sorry for the slow response. The load ratio is a measure of the total request time to the compute time. It gives you an understanding of how loaded the server is. For example, if the ratio is 2.0, it means that the request time is taking 2x the inference (compute) time.... so the request is taking 2x the ideal time it could be (likely due to having to be queued due to other requests using the inference contexts).

https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/server_status.cc#L412
