### ISSUE TITLE
memlock can not be setted in k8s

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/tensorrt-inference-server#307]
Hello,
    With docker starting, it's easy to add the option "--ulimit memlock=-1", But it's not allowed to do this when deploy with k8s. I try to use command line : ulimit -l unlimited but failed because it only allow to set a lower value.
    What I concerned is what will happend when this option is not setted. If it just has a little affect on performance, then it does not matter. I worry about any crash would happed if this option not setted.

**Comment by deadeyegoodwin** [comment]
You should be able to safely remove that flag. It is needed so that we can lock memory pages to make Host<->GPU memory transfers faster. However, TRTIS does not yet take advantage of that feature. Even once TRTIS implements page locking it should not crash if unable to lock pages.

BTW, we now include a Helm Chart for deploying TRTIS that you might find useful: findhttps://github.com/NVIDIA/tensorrt-inference-server/tree/master/deploy/single_server
