### ISSUE TITLE
No PYVER in Dockerfile.client

### ISSUE THREAD

**Issue by bezero** [NVIDIA/tensorrt-inference-server#311]
As it is explained in [Build Using Dockerfile](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/client.html?highlight=pyver#build-using-dockerfile), to build a client with different Python version you can optionally add ```--build-arg “PYVER=<ver>” ```. However, [Dockerfile.client](https://github.com/NVIDIA/tensorrt-inference-server/blob/r19.05/Dockerfile.client) does not contain ```ARG PYVER```.

**Comment by GuanLuo** [comment]
We updated the Dockerfile.client and the client build files so that the wheel file generated doesn't target to specified Python version. Thus `ARG PYVER` is dropped. What's more, you can now specify the Ubuntu version (16.04 / 18.04) you want to build the client container on by specifying `--build-arg "UBUNTU_VERSION=<ver>"`.

The [doc update](https://github.com/NVIDIA/tensorrt-inference-server/blob/e3c75f8d2f0627139c184f6fa12670247f126e96/docs/client.rst) is done in a later commit, which causes the misalignment.

**Comment by nadiia-pyvovar** [comment]
Is there a way to specify the version of python then? When I build client from r19.05, all of the dependencies install under python2.7. 
This causes `python3 ensemble_image_client.py qa/images/mug.jpg` to throw a dependency error when `python ensemble_image_client.py qa/images/mug.jpg` works just fine. 
Maybe I need something else to run under python3?

**Comment by deadeyegoodwin** [comment]
You must have both python2 and python3 on your system. Did you install the wheel with pip or pip3?

**Comment by bezero** [comment]
@nadiia-pyvovar as far as I know if you build client from ```Dockerfile.client```, it will install the ```.whl``` to python2.7 with ```RUN pip install --upgrade install/python/tensorrtserver-*.whl numpy pillow``` command. Since the ```.whl``` that is built is independent of the Python version, you can modify ```Dockerfile.client``` and add pip3 and install using pip3. It should be something like:
```
RUN apt install python3-pip && pip3 install --upgrade install/python/tensorrtserver-*.whl numpy pillow
```
