### ISSUE TITLE
Impact of "instance-group" option

### ISSUE THREAD

**Issue by JungukCho** [NVIDIA/tensorrt-inference-server#366]
Hi, 

I asked this question before (How to use different max_batch_size configurations for version? #168 )

I have a following 3rd question (i.e., If I configure 1024 as max_batch_size in inference server, are 1024 inputs processed in parallel at GPU or copied from host to device as batch?
In case of it processed 1024 inputs at the same time when I configure 1024 as max_batch_size and count value in instance-group as 2, it means 2048 inputs are computed simultaneously in GPU?)

About this question, I measured time to see perfomance accoding to "instance-group" values.
Based on my understanding and your response, I expected no significant execution time increase.
However, when I compared one instance-group against two instance-group, the execution time is almost double.

For example, with one instance-group in a trtis and one inference request from a client
batch size in one request | nv_inference_request_duration_us | nv_inference_compute_duration_us | nv_inference_queue_duration_us
1 | 8.0314 | 7.7838 | 0.0512
2 | 12.0954 | 11.7924 | 0.0678
4 | 17.0856 | 16.7118 | 0.059

With two instance-group in a trtis and two inference requests from a client
batch size in each request | nv_inference_request_duration_us | nv_inference_compute_duration_us | nv_inference_queue_duration_us
1 | 13.0091 | 12.8392 | 0.0481
2 | 18.7193 | 18.507 | 0.0477
4 | 31.9959 | 31.7148 | 0.058

I expected two cases shows similar numbers since two CUDA streams enable parallel request process and the number of requests is small.
Is it an expected result?

**Comment by deadeyegoodwin** [comment]
How much speedup you can get from using multiple instances depends on how large your model is and how much of the GPU it occupies. For example, assume you have a large model that uses most of the GPU compute and memcpy bandwidth when executing a batch-size 4 inference (utilization is 85-95%):
- using instance-group to allow 2 model executions at the same time will likely not result in much speedup. The GPU is (nearly) fully utilized running one instance of the model, so it doesn't have spare capacity to run the second instance. Instead, the 2 instances share the GPU, each performing at about 50%.
- using a single instance with batch-size 8 will likely not result in much speedup. Again because the batch-size 4 inference is using nearly all the GPU there isn't excess compute or memcpy capability to use for a large batch size.

The above are general statements... there may be some variation depending on if the GPU is more compute bound or memcpy bound for a given model.

**Comment by JungukCho** [comment]
Hi, 

Thank you for response.
I used a converter to generate plan file from inception.v3 model.
This experiment was done with V100 GPU which is very high-end GPU.

Since GPU memory usage is based on the size of batch, TRTIS does not reserve large size of GPU memory for small size of batch. Also, I think GPU utilization is proportional according to the number of batch.
Since V100 is very high-end GPU, a batch-size 4 inference will not saturate V100 resource.

To dive into this, I think I need a nice tool to monitor GPU usages.
Is there a tool to collect fine-grained GPU utilization?  As far as I know, the output from  "nvidia-smi" is not fine-grained utilization.

**Comment by nieksand** [comment]
https://developer.nvidia.com/performance-analysis-tools

**Comment by deadeyegoodwin** [comment]
@JungukCho nvidia-smi isn't the most precise tool but it can give you a rough measure of how much GPU your model utilizes. Just run  "nvidia-smi -l 1" and then use perf-client to run continuous requests and see what the utilization is. If your single-instance model is using only 40% GPU then it is likely that 2 instances should provide some improvement. If you see 80-90% GPU utilization then it is likely that you won't see much improvement.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you are still seeing unexpected results.
