### ISSUE TITLE
Ensembling and varying batch sizes

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#443]
Can the following situation be modeled using the current implementation of ensembling:
A model A takes as input an image (batch size 1) and produces a varying number of crops from this image (think object detector+postprocessing). A model B takes as input (batch size 1) one of these crops (think feature extractor). A batch size 1 input of A would yield a batch size >= 1 input for B. How can A and B be ensembled?

**Comment by GuanLuo** [comment]
The ensemble assumes that the batch size is the same between all models. However, you can bypass this by setting your models' `max_batch_size` to 0 and including the batch dimension into your models' inputs and outputs. In this way, you are in charge of batching instead of the ensemble / TRTIS.

For instance:
```
max_batch_size: 8
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
```
becomes:
```
max_batch_size: 0
input [
  {
    name: "INPUT0"
    data_type: TYPE_FP32
    dims: [ -1, 16 ]
  }
]
output [
  {
    name: "OUTPUT0"
    data_type: TYPE_FP32
    dims: [ -1, 16 ]
  }
]
```

**Comment by mrjackbo** [comment]
Thanks for the answer! This also works for TensorRT plans?

**Comment by GuanLuo** [comment]
I don't think so, compared to other framework models, TRT plans have fixed `max_batch_size` instead of variable size (-1), so it does not make sense to append -1 to the tensor dims (and appending the actual `max_batch_size` will make TRTIS to expect every request to the TRT plan is in "full batch").
