### ISSUE TITLE
perf_client with user-defined data and variable size

### ISSUE THREAD

**Issue by damitkwr** [NVIDIA/tensorrt-inference-server#444]
Hi, 

I am load testing a custom model with the perf_client.cc file. I see that it has a --data-directory argument which I have created. The files are in the name of the inputs and in numpy binary representation of the inputs. Here is an example:

data /
---- source
---- source_len

Please note that the two files are in binary format given by the .tobytes() function from the numpy library.

Whether I specify the data-directory or not it seems that I am getting this error:

> Thread [0] had error: [ 0] INVALID_ARG - input 'source' has variable-size shape, unable to create input values for model 'spelling_model'

Please let me know if I have either specified the data wrong or is passing the argument wrong. Thanks!

**Comment by deadeyegoodwin** [comment]
perf_client can't work with models with variable-sized inputs because it doesn't know what size (and shape) of data to send. For performance testing purposes you just need to change your model configuration to have all fixed dimensions. That will allow you to use perf_client to performance test with those specific input sizes.
