### ISSUE TITLE
Dynamic input and output shape definition for object detection

### ISSUE THREAD

**Issue by gr8Adakron** [NVIDIA/tensorrt-inference-server#447]
I have this object detection model which works fine in the tf-serving and I am trying to deploy it on the tensorrt as well, but the issue I am facing- in tf-serving I do not need to define the input_shape and output_shape of the tensors which is considered directly from the model-file itself and works as well. But in tensorrt, I have to manually define those shapes and I can't escape that as the config-error is getting encountered.

This is the definition of my input tensor:

> 
> [{'name': **'input_1', 'shape': '(?, ?, ?, 3)',** 'dtype': "<dtype: 'float32'>"},
>  {'name': 'pyramid_regression_0/kernel',
>   'shape': '(3, 3, 256, 256)',
>   'dtype': "<dtype: 'float32'>"}]
> 
> 
> 

And this is the config.pbtxt

```
name: "objdtc_trt"
platform: "tensorflow_graphdef"
max_batch_size: 16
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 224, 224, 3 ]
  }
]
output [
  {
    name: "output_1_1"
    data_type: TYPE_FP32
    dims: [ 224 ]
  },
  {
    name: "output_1_2"
    data_type: TYPE_FP32
    dims: [ 224 ]
  },

]
instance_group [
  {
    gpus: [0]
  }
]

```

Is there a way, where I can define the input and output tensor dynamically- the dimensions.

**Comment by gr8Adakron** [comment]
@swarren @mkolod @lukeyeager

**Comment by GuanLuo** [comment]
If you are referring to variable size tensor, then you can simply mark the variable size part to -1 (see [detail](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#model-configuration)). And you can actually provide no model config and set `--strict-model-config=false` on starting TRTIS, which will auto-fill the model config for you if the framework supports it (see [detail](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#generated-model-configuration)).

If it is not variable size tensor that you are referring to, please provide more detail and the error message you encountered so that we can have a better understanding of the issue.
