### ISSUE TITLE
Deploying TF-serving SavedModel format to TRT-5.1.5 without conversion

### ISSUE THREAD

**Issue by gr8Adakron** [NVIDIA/tensorrt-inference-server#457]
Hey,

I already have one image-segmentation model, which is TF-serving SavedModel model format and it works fine- with the TF-serving inference.
I have been migrating all the models to TRT-5.1.5-inference-server, obviously for the performance efficiency. I did the conversion for other models (ie: classification, object-detection) and it wasn't that complex, but as I trying to convert this image-segmentation model- the file after conversion isn't as big as others, seems like there nothing in the converted graph.

My conversion Script:
```
from tensorflow.python.framework import graph_util
from tensorflow.python.framework import graph_io
import tensorflow as tf

node_info_list_dict = []
export_path         = "/home/serving/serving_models/segmentation/5"

with tf.Session(graph = tf.Graph()) as sess:
    tf.saved_model.loader.load(sess, ["serve"], export_path)
    graph             = tf.get_default_graph()
    nodes_list        = graph.get_operations()
    #print(nodes_list)


for op in graph.get_operations(): 
    for val_obj in op.values():
        #print(str(val_obj.shape))
        node_info_list_dict.append(
            {
                "name" : op.name,
                "shape": str(val_obj.shape),
                "dtype": str(val_obj.dtype),
            }
        )

constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(), [node_info_list_dict[-1]["name"]])    
graph_io.write_graph(constant_graph, "segmentation_trt", "model.graphdef", as_text=False)

```
_**This script worked for other models.**_

The model structure before conversion **(tf-serving format)**:
![trt-issue](https://user-images.githubusercontent.com/16715364/61181167-f7ad7000-a63f-11e9-842e-b5466c3b7d09.png)
Size of the file inside it:

> 
> -rw-rw-r-- 1 serving serving **531K** May 27 09:18 5/saved_model.pb
> -rw-rw-r-- 1 serving serving **5.6K** May 27 09:18 5/variables/variables.index
> -rw-rw-r-- 1 serving serving **424M** May 27 09:19 5/variables/variables.data-00000-of-00001
> 
> 

Size of the files after conversion:

> -rw-rw-r-- 1 serving serving **4.5K** Jul 13 07:39 model.graphdef

I am not sure what going wrong here. 

**OR**
**_Is there a way to deploy the TF-serving SavedModel format which works with the TF-serving inference directly to TRT-5.1.5 inference_**- that would be really helpful as the conversion is very time-consuming. As in my case having 100s of models.

Any help is appreciated.

**Comment by gr8Adakron** [comment]
@swarren @mkolod @lukeyeager

**Comment by deadeyegoodwin** [comment]
Model conversion should work on your model, or you should get some sensible error message as to why it failed. However:

1. The script you attached just converts saved-model format to graphdef format (and I think you may even be missing something for that). Both of those are TensorFlow graph formats... I don't see anything related to TensorRT in there.
2. TensorRT is a related but different technology/project from TensorRT Inference Server (TRTIS). It is unfortunate that they share (partially) the same name.
3. If you are trying to convert your TF models to TRT then you are missing steps from your conversion script and you should ask for help in the TRT forum: https://devtalk.nvidia.com/default/board/304/tensorrt/
4. If you want to serve your TF saved-model using TRTIS then you don't need to do any conversion because TRTIS supports saved-model format (as well as TF graphdef, ONNX, Caffe2, PyTorch, and TensorRT). You just need to create your model repository as described here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models
