### ISSUE TITLE
CMake build error r19.07

### ISSUE THREAD

**Issue by banuprathap** [NVIDIA/tensorrt-inference-server#490]
Hi,
I am trying to compile r19.07 from source on Jetson Nano with CMake version 3.10.2 
I followed the instructions from [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/docs/build.rst) and I get the following error.

> CMake Error at /home/banu/tensorrt-inference-server/src/core/CMakeLists.txt:33 (protobuf_generate_cpp):
>   Unknown CMake command "protobuf_generate_cpp".

Please help

**Comment by deadeyegoodwin** [comment]
A couple of things:
- 19.07 hasn't released yet so you may not be able to build it yet (as is noted in the README for that branch). 19.07 should release later this week.
- You should look at the docs for the r19.07 branch since that is what you are attempting to build. Those docs mention that when you get this error you just need to "make" again and it will be fixed https://github.com/NVIDIA/tensorrt-inference-server/blob/r19.07/docs/build.rst
- This build issue is fixed on the master branch: https://github.com/NVIDIA/tensorrt-inference-server/pull/478
