### ISSUE TITLE
Allow manual batching for TensorRT plans with max_batch_size=0

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#509]
This is a feature request arising from issue #443.

Given a TensorRT plan with max batch size `N`, and input of shape `[d_0,d_1,...]`, I would like to be able to 

- set `max_batch_size=0` in the TRTIS config.pbtxt,
- set the input shape to `[-1,d_0,d_1,...]`,
- send tensors of shape `[n,d_0,d_1,...]` to TRTIS, where  `0 < n <= N`,
- and of course receive a batch of inference results of size `n`.

As of writing, to my knowledge, TRTIS does not allow such a configuration, complaining that TensorRT plans do not allow inputs of variable size.

**Comment by deadeyegoodwin** [comment]
You are correct that TensorRT doesn't allow arbitrary variable-size dimensions, but it does allow the first dimension to be a variable-size batch dimension. So your case above is handled today. I think your request has to do with an ensemble having both batching and non-batching models. There was a recent PR to help this case in some limited situations, and we have a plan to improve it more generally. @GuanLuo can you provide some details in see if what we have done so far is enough to help @mrjackbo

**Comment by GuanLuo** [comment]
As mentioned in the issue you linked, the model config for TensorRT is still being strict on no -1 dimension. The recent change is allowing reshaping on the dimensions separated by the variable-size dimensions, for instance, now reshape from [ 2, 4, -1, 6 ] to [ 8, -1, 1, 6 ] is allowed.

We are planing on relaxing the tensor shape comparison between models in ensemble, which may be helpful for your case. Instead of comparing the input / output shape alone, batching or not will also be considered. For instance, if you have a batchable TensorRT model with output shape [ 16 ] and a non-batchable ONNX model with input shape [ -1, 16 ], then the ensemble will expand the output from TensorRT model to [ n, 16 ] and feed it to the ONNX model as its input shape [ -1, 16 ] can consume [ n, 16].

**Comment by mrjackbo** [comment]
> For instance, if you have a batchable TensorRT model with output shape [ 16 ] and a non-batchable ONNX model with input shape [ -1, 16 ], then the ensemble will expand the output from TensorRT model to [ n, 16 ] and feed it to the ONNX model as its input shape [ -1, 16 ] can consume [ n, 16].

This is exactly the case opposite to mine. I want to feed output of shape `[-1,16]` to a batchable TensorRT plan with input shape `[16]`.

I suppose I just need a way around the TRTIS check that the batch dimension of a TensorRT plan cannot be `-1`.

**Comment by GuanLuo** [comment]
@mrjackbo the non-batchable to batchable case will also be handled, since we need both ways so that the ensemble input and output can agree with each other in terms of batch size..

**Comment by GuanLuo** [comment]
@mrjackbo #526 implemented the plan I mentioned above, and you can also refer to this [test case](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/qa/ensemble_models/mix_nobatch_batch_float32_float32_float32/config.pbtxt) to see if this change fits your need. And please re-open the issue if it doesn't
