### ISSUE TITLE
Output shape with Pytorch model 

### ISSUE THREAD

**Issue by netpcvnn** [NVIDIA/tensorrt-inference-server#543]
Dear all, 
I tried to deploy the Pytorch model in the Inference server But I got the error when do the inference call to the server. 
The error: `tensorrtserver.api.InferenceServerException: [inference:0 3] unexpected shape for output 'out__0', model configuration shape is [20,37], inference shape is [20,37]`
The output node in the config.pbtxt file: 
`output [
  {
    name: "out__0"
    data_type: TYPE_FP32
    dims: [20, 37]
  }`
Anyone know what the problem?

**Comment by CoderHam** [comment]
The model probably expects a batch but you aren't passing a batch (Try passing a batch of size 1 instead i.e [20, 37] or don't set the max_batch_size if you aren't using batching.

**Comment by netpcvnn** [comment]
Thank you for your support.
When I try to pass a batch of size 1, I got this error: `tensorrtserver.api.InferenceServerException: [inference:0 3] unexpected shape for output 'OUTPUT__0', model configuration shape is [20,37], inference shape is [1,20,37]. 
`. The output node as: `output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: 1
    dims: 20
    dims: 37
  }
]
`
I also don't set the max_batch_size or set max_batch_size = 0, I have this error `tensorrtserver.api.InferenceServerException: [inference:0 3] failed to run model 'address_0_0_gpu0`

**Comment by CoderHam** [comment]
Is it possible for you to share you model and config file?

**Comment by netpcvnn** [comment]
Yes, I can share the model and config file.
You can find in [this link](https://drive.google.com/file/d/1dYHtczNSPYdmD7vBl0ZDiWqaM6EjdNGE/view?usp=sharing)

**Comment by netpcvnn** [comment]
@CoderHam Do you have time to test my model?

**Comment by CoderHam** [comment]
There was an issue with the error message being reported.

> INVALID_ARG - unexpected shape for output 'OUTPUT__0', model configuration shape is [20,37], inference shape is [20,37]

The output 'OUTPUT__0' for some reason is missing the batch dimension. Since the batch size is 1 and the model supports batching, the resultant output from the model should be [1, 20, 37] but the model outputs [20, 37]. 

The reason the error above does in fact makes sense is because for a model that supports batching, the output should have an extra batch dimension i.e. in this case [1, 20, 37] instead of [20,37]. (And from my understanding, the model config should be:

```
...
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: 20
    dims: 37
  }
]
...
```

**Comment by netpcvnn** [comment]
Thanks @CoderHam,
 I have tried the output as your suggestion but I got the error: `tensorrtserver.api.InferenceServerException: [inference:0 10] unexpected shape for output 'OUTPUT__0', model configuration shape is [20,37], inference shape is [20,37]`.

**Comment by CoderHam** [comment]
@netpcvnn I suspect this is because the model does not support batching correctly (as explained above)
Why don't you use the pytorch model you used to create the jitted model and see what the output for that model is for a batch size of 1. It should be [1,20,37] and not [20,37] (Which is what you are getting).

TRTIS assumes that if batching is enabling then Inputs for `batch-size = 1` would be such that:
```
Input 'INPUT__0' has shape: [1,1,32,100]
Input 'INPUT__1' has shape: [1,1]
Input 'INPUT__2' has shape: [1,5]
Input 'INPUT__3' has shape: [1,5]
```

Similarly, it expects the Output for `batch-size = 1` to be such that: 
```
Output 'OUTPUT__0' has shape: [1,20,37]
```
You must simply fix the output for your model to including the batch-dimension. Once that is done your model should work fine.

**Comment by netpcvnn** [comment]
Thanks @CoderHam. Looks like batching in my model has problems.
