### ISSUE TITLE
Does TF-TRT used in TRTIS tensorflow runtime engine? 

### ISSUE THREAD

**Issue by pengchengu** [NVIDIA/tensorrt-inference-server#597]
Hi,
I know that TRTIS is a different technology from TRT, and a Tensorflow graphdef model deplyed in TRTIS is driven by a tensorflow runtime engine not by a TRT runtime engine.

But i noticed in the Documention of TRTIS, "TensorFlow 1.7 and later integrates TensorRT to enable TensorFlow models to benefit from the inference optimizations provided by TensorRT. " Does this means TF-TRT is used inside TRTIS tensorflow runtime engine to accelerate Tensorflow models?

If not，does TRTIS adopt any other techniques to accelerate non-TRT models?

**Comment by deadeyegoodwin** [comment]
You can generate a TF-TRT model from a tensorflow model as shown in these examples: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usage-example

The resulting model will be a tensorflow saved-model that you can load in TRTIS and it will run it correctly. So in this way TRTIS does support TF-TRT models.

In our backlog we also have plans to add a TRTIS option so that you can turn on the TF-TRT optimization option by a setting in the model configuration.

In general TRTIS relies on the underlying framework to optimize the model. There are some controls exposed through the optimization section of the model configuration: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/model_config.proto#L368

**Comment by thebruce87m** [comment]
> You can generate a TF-TRT model from a tensorflow model as shown in these examples: https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#usage-example
> 
> The resulting model will be a tensorflow saved-model that you can load in TRTIS and it will run it correctly. So in this way TRTIS does support TF-TRT models.
> 
> In our backlog we also have plans to add a TRTIS option so that you can turn on the TF-TRT optimization option by a setting in the model configuration.
> 
> In general TRTIS relies on the underlying framework to optimize the model. There are some controls exposed through the optimization section of the model configuration: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/model_config.proto#L368

Do I still need to convert my model as per the example or are there now options on the (jetpack version) triton server to do this? Thanks!
