### ISSUE TITLE
How to preserve request / response order with the callback version of AsyncRun?

### ISSUE THREAD

**Issue by aleksa2808** [NVIDIA/tensorrt-inference-server#641]
In the image_client example, to preserve the order of requests / responses, a deprecated version of the AsyncRun method is used. There, we save the sent request objects to a queue, then wait on them one-by-one.

Since, in a future version of TRTIS, we'll only be able to use the callback version of AsyncRun, how is this order-preserving functionality intended to be implemented with it?

**Comment by GuanLuo** [comment]
You can keep track of the ordering in your callback by capturing additional information. For instance, [lambda capture](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/simple_callback_client.cc#L218) in C++ client library, and "partial" in Python client library.

**Comment by deadeyegoodwin** [comment]
A python example that uses a queue is here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/simple_callback_client.py

**Comment by aleksa2808** [comment]
Ok, but with the removal of the request-based AsyncRun method, in the case where the order of the requests is important, users are now required to do the synchronization logic on their end. Is this correct?

Also, are there any plans to update the image_client example by removing the use of the deprecated method?

**Comment by deadeyegoodwin** [comment]
Firstly, the API is just deprecated... it is not being removed. Perhaps in a future iteration of the client library it will be removed but we don't currently have any plans for that.

You always had to do your own sync logic because you needed to wait for the response (either by blocking on the API or some other method. You can still do that with the callback API, you just need to provide the callback function to collect the request IDs.
