### ISSUE TITLE
Update Protobuf dependencies

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#705]
Protobuf fails to compile using cmake on Raspbian Buster. 

This issue is solved by protobuf [here].(https://github.com/protocolbuffers/protobuf/commit/55ed1d427ccc0d200927746329ac9b811dee77b9)

So you only have to update the dependency.

Related issue:
https://github.com/mavlink/MAVSDK/issues/836

Build Failure:
```
[ 98%] Building CXX object CMakeFiles/libprotoc.dir/home/pi/Documents/tensorrt-inference-server/build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/compiler/zip_writer.cc.o
[ 98%] Linking CXX static library libprotoc.a
[ 98%] Built target libprotoc
Scanning dependencies of target protoc
[ 99%] Building CXX object CMakeFiles/protoc.dir/home/pi/Documents/tensorrt-inference-server/build/grpc-repo/src/grpc/third_party/protobuf/src/google/protobuf/compiler/main.cc.o
[100%] Linking CXX executable protoc
/usr/bin/ld: libprotobuf.a(arena.cc.o): in function `google::protobuf::internal::ArenaImpl::Init()':
arena.cc:(.text+0x4e8): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
make[6]: *** [CMakeFiles/protoc.dir/build.make:87: protoc] Fehler 1
make[5]: *** [CMakeFiles/Makefile2:185: CMakeFiles/protoc.dir/all] Fehler 2
make[4]: *** [Makefile:130: all] Fehler 2
make[3]: *** [CMakeFiles/protobuf.dir/build.make:112: protobuf/src/protobuf-stamp/protobuf-build] Fehler 2
make[2]: *** [CMakeFiles/Makefile2:371: CMakeFiles/protobuf.dir/all] Fehler 2
make[1]: *** [CMakeFiles/Makefile2:614: CMakeFiles/trtis-clients.dir/rule] Fehler 2
make: *** [Makefile:300: trtis-clients] Fehler 2

```

**Comment by deadeyegoodwin** [comment]
Protobuf is a little bit of a disaster to work with due to how version touchy it is. To roll protobuf forward we have to do so in conjunction with our grpc build (we use the protobuf from the grpc repo). You can look in build/CMakeLists.txt to see which grpc version we are using and if that can be rolled forward to a newer version that has the updated protobuf. Alternatively you can apply a patch which we also do in CMakeLists.txt with PATCH_COMMAND in a few places.

**Comment by ohlr** [comment]
Thanks for the hints. I solved the issue by switching my [OS](https://github.com/NVIDIA/tensorrt-inference-server/issues/703).
