### ISSUE TITLE
Provide test harness for custom backends

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#772]
It would be very helpful if the custom backend sdk would contain a minimal harness with which to load and execute custom backends, e.g. for unit tests and benchmarks.

I tried to cook up such a harness, but it seems the sdk does not contain a way to read the model config in protobuf::textformat. Thus the I would have to link against the correct version of protobuf, which is complicated by the fact, that the server is built in a container. 

Am I missing a simple solution (using only the SDK zip) here?

**Comment by mrjackbo** [comment]
I am using the 19.09 release at the moment. The problem for me is providing valid input to `CustomInitialize` using just the SDK.  `CustomInitialize` uses `ModelConfig::ParseFromString`, which expects a protobuf in binary format, while the config files are pbtxt. So the only way I could figure out was to link against the correct version of protobuf, and then use`::google::protobuf::TextFormat::ParseFromString` (as done in trtis' filesystem.cc) followed by `ModelConfig::SerializeAsString`. The resulting string can be passed to `CustomInitialize` via `CustomInitializeData`. If the SDK would provide some way to deserialize a config.pbtxt, I would not need to keep my own protobuf in sync with trtis'.

I have a few custom backends that are working well already. My usual workflow is: Unit test the core functionality, wrap it in a `CustomInstance`, then integration test it against the server. It would be more convenient to also have tests against `CustomInstance` (for example to make sure the inputs are checked correctly, and for benchmarking/tuning purposes). Because of the protobuf issue, I do not see how this is possible just using the SDK (as of 19.09). 
Thanks for the great project btw!

**Comment by deadeyegoodwin** [comment]
I think you mean "... provide some way to serialize a config.pbtxt". Deserialization is provided by ParseFromString.

Anyway, it seems we are not including the TextFormat portion of the protobuf library to make it possible to ready textual representation of a protobuf. We will look into that.

**Comment by mrjackbo** [comment]
> I think you mean "... provide some way to serialize a config.pbtxt". Deserialization is provided by ParseFromString.

As I said, it is not clear to me, how to correctly pass a config.pbtxt to `ModelConfig::ParseFromString`, as the latter seems to expect a protobuf in binary format.

**Comment by deadeyegoodwin** [comment]
I pretty sure you just need the SDK to include the TextFormat routines from protobuf and then you will be able to do what you want. It shouldn't be too hard for us to fix... we will update when we do.

**Comment by deadeyegoodwin** [comment]
I took a look at the custom backend SDK and I think it already has everything you need... or else I don't understand your request. The libcustombackend.a included in the SDK has all the protobuf functions, including the TextFormat functions. You can see them using "nm" on the library. The test_format.h include file is also available in include/google/protobuf.

So that means that you should be able to use google::protobuf::TextFormat::ParseFromString() to convert a config.pbtxt to the corresponding ModelConfig object/message.  You can then use config.SerializeToString to create a serialization of the model config that you then pass to the custom backend init function, as is done here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/backends/custom/custom_backend.cc#L242

**Comment by mrjackbo** [comment]
Ah, thanks. I did not see that the SDK contains the google headers. Sorry about the confusion.
