### ISSUE TITLE
How to config input has shape:  <unknown> ?

### ISSUE THREAD

**Issue by HoangTienDuc** [NVIDIA/tensorrt-inference-server#775]
I try to deloy my model using trtis. 
I have 2 inputs like below:
```
input_tensor_names:  img_inputs:0
shape:  (?, 112, 112, 3) 
input_tensor_names:  dropout_rate:0
shape:  <unknown>   -> for example: 0.5
```
i dont how to config my model in this case

**Comment by deadeyegoodwin** [comment]
What framework are you using (onnx, TensorRT, etc.). The easiest way for most frameworks is to have TRTIS generate the configuration for you by using --strict-model-config=false. See https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_configuration.html#generated-model-configuration

**Comment by GuanLuo** [comment]
Is the input `dropout_rate` a scalar value? If so, because TRTIS doesn't recognize a scalar input, you will need to modify your model so that it is exposed as a tensor with shape [1], or to hide it by feeding a constant to it.

In your case, the name `dropout_rate` suggests that it is exposed as input for training, so you may want to make it a constant 0 for inference.

**Comment by deadeyegoodwin** [comment]
Closing. Re-open if you still have problems generating a model configuration.
