### ISSUE TITLE
HTTP allocation failed

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#843]
This is more sort of a question.
For some models I see the following error getting triggered: `HTTP allocation failed for type...` by
https://github.com/NVIDIA/tensorrt-inference-server/blob/e053b65fcda8981dbe1d01a743ebd78143dbff5f/src/servers/http_server.cc#L365

Reading through the documentation left me clueless about how I could resolve this error and how big of an error it is.
The error occurs for TRT models only so far. Do I need to change my model or the (python) client?

**Comment by deadeyegoodwin** [comment]
Can you share the console log where you are seeing this error, and also the version of TRTIS you are using. Those messages are just verbose log messages, not errors. We can change the message to sound less like an error.

**Comment by GuanLuo** [comment]
As @deadeyegoodwin mentioned, this is a verbose log instead of an error.

To elaborate more on what is going on, this conditional will be hit when a backend supports GPU outputs (i.e. Libtorch, TensorRT). In that case, the backend will "prefer" to store the outputs as close to the model instance as possible (i.e. same GPU device). But since HTTP / GRPC needs to transfer the data via network, the output will need to be stored in system memory.

The backend's "preference" is taken into the consideration for reducing overhead in ensemble. For instance, if all models are deployed in GPU 0, then the data transfer between host and device may be minimized.

**Comment by deadeyegoodwin** [comment]
Fixed by #845.

**Comment by ohlr** [comment]
Thank you all for the clarification.
