### ISSUE TITLE
python not found

### ISSUE THREAD

**Issue by MachineJeff** [NVIDIA/tensorrt-inference-server#857]
**Description**
I used the following code to get into the container:

```
docker run -it nvcr.io/nvidia/tensorrtserver:19.06-py3
```

the I was confused:
```
root@bc56189996f0:/opt/tensorrtserver# python
bash: python: command not found
```
why?

**TRTIS Information**
nvcr.io/nvidia/tensorrtserver:19.06-py3

**System Information**
GPU Type: Tesla T4
Nvidia Driver Version: 418.87.01
CUDA Version: 10.1.243
CUDNN Version: 7.6.3
Operating System + Version: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-142-generic x86_64)

**Comment by deadeyegoodwin** [comment]
The 19.06 version of TRTIS does not require python so it is not in the container. The py3 in the container name is something of an artifact of how NVIDIA names the containers. If you want python in the container you can install it.
More recent versions of the container do contain python because it is needed for the OpenVino ONNX Runtime backend.
