### ISSUE TITLE
any plan for client sdk in other languages? 

### ISSUE THREAD

**Issue by zw0610** [NVIDIA/tensorrt-inference-server#867]
**Is your feature request related to a problem? Please describe.**
So far, there seems only Python, C++ and Go client SDKs. However, when we develop client, like on iOS or Android or for a web browser, neither is widely used (I might be wrong).

**Describe the solution you'd like**
A JS/Java/Swift sdk might be helpful.

**Describe alternatives you've considered**
I'm not sure about the philosophy behind the TRTIS client. Will Nvidia provide different SDKs on various languages or the client code (in this repo) is just an example and users are expected to write the SDKs on other languages?

**Additional context**

**Comment by deadeyegoodwin** [comment]
We provide a C++ and Python client library to make it easy for users to write client applications that communicate with TRTIS. We chose those languages because they were likely to be popular and performant in the ML inference space, but in the future we could possibly do another language if there was a need.

We provide the GRPC API as a way to generate your own client library for a large number of languages. By following the official GRPC documentation and using src/core/grpc_service.proto you can generate language bindings for all the languages you mention, and many more. We provide two examples of this:
- Go: https://github.com/NVIDIA/tensorrt-inference-server/tree/master/src/clients/go
- Python: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/grpc_image_client.py.

In general the client libraries (and client examples) are meant to be just that, examples. We feel the client libraries are well written and well tested, but they are not meant to serve every possible use case. In some cases you may want to develop your own customized library to suit your specific needs.

**Comment by zw0610** [comment]
@deadeyegoodwin Thank you for your response. We might try gRPC with other languages on our own cases.

**Comment by seovchinnikov** [comment]
I've made PR for java/kotlin
https://github.com/NVIDIA/tensorrt-inference-server/pull/966
