### ISSUE TITLE
Docs provided to create local cmake build trt inference server with Tensorflow not working properly or don't have enough information to build the required builds

### ISSUE THREAD

**Issue by balacs123** [NVIDIA/tensorrt-inference-server#899]
Here I have attached few one of the issue we faced

/home/ubuntu/balaSandbox/trtis/tensorrt-inference-server/build/protobuf/include/google/protobuf/arena_impl.h(310): warning: integer conversion resulted in a change of sign

/home/ubuntu/balaSandbox/trtis/tensorrt-inference-server/src/custom/addsub/addsub.cu(57): warning: overloaded virtual function "nvidia::inferenceserver::custom::CustomInstance::Execute" is only partially overridden in class "nvidia::inferenceserver::custom::addsub::Context"

/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
make[4]: *** [all] Error 2
make[3]: *** [trtis-custom-backends/src/trtis-custom-backends-stamp/trtis-custom-backends-build] Error 2
make[2]: *** [CMakeFiles/trtis-custom-backends.dir/all] Error 2
make[1]: *** [CMakeFiles/trtis-custom-backends.dir/rule] Error 2
make: *** [trtis-custom-backends] Error 2
(base) ubuntu@ip-172-31-10-186:~/balaSandbox/trtis/tensorrt-inference-server/build$

We are also looking for clear documentation to create local cmake builds

**Comment by deadeyegoodwin** [comment]
The first is a warning building protobuf. We don't control how protobuf is built but I agree that it would be nice if they would clean up all their build warnings. You can file an issue with the protobuf project and see if they will fix.

The second are warnings/errors from building the TRTIS custom backends, not the server itself. But still those errors are unexpected. They are likely due to your build system being something we don't explicitly test. What is the OS and compiler you are using.

**Comment by deadeyegoodwin** [comment]
Closing for non-activity.
