### ISSUE TITLE
Request batch size greater than max_batch_size

### ISSUE THREAD

**Issue by Arun4rangan** [NVIDIA/tensorrt-inference-server#903]
**Is your feature request related to a problem? Please describe.**

I am using similar setup to #443. 
Model 1 : Preprocessing an Image  (Custom backend)
Model 2 : Finds objects within Image 
Model 3 : Finds features within objects

Model 2 results in lots of objects, and is greater than max_batch_size on Model 3. 

**Describe the solution you'd like**

Is it possible to use dynamic_batching to slice the results from Model 2 and queue up inference requests on model 3?

**Comment by deadeyegoodwin** [comment]
The inference server will combine multiple requests together for inferencing (dynamic batching), but it will not split a too-large batch into smaller batches. The client generating the inference requests must ensure that the batch size of any requests is <= max_batch_size supported by the model.

**Comment by Arun4rangan** [comment]
@deadeyegoodwin is it possible to call model 3 multiple times from custom backend model in between model 2 and model 3?

If not, would you accept a PR that allows slicing matrix into preferred preferred_batch_sizes ?

Thanks!

**Comment by deadeyegoodwin** [comment]
No, a custom backend can only consume and produce tensors, and for any given inference request a given custom backend will run at most once. If you want to have more complex control flow I suggest you consider an "application server" that sits next to TRTIS that performs the complex control-flow and other operations needed for your algorithm / pipeline. Your "application server" can use shared memory to communicate with TRTIS so that the overhead of server<->TRTIS communication will be very low. 

A similar alternative is to use the API provided by the TRTIS shared library to build TRTIS functionality into your application.
